### ISSUE TITLE
Add light/dark mode

### ISSUE THREAD

**Issue by linyanna** [MLH-Fellowship/prep-project-22.AUG.PREP.2#17]
Either add a toggle to configure a light/dark mode manually or automatically adjust to system settings. Or perhaps for more in-app theme integration, automatically configure the light/dark theme to the time zone of the searched location.

**Comment by farida52369** [comment]
Thinking of the issue, adding dark mode won't change anything except the place where the weather type appears as the color is blue and won't change in dark mode .. So if u can tell me your expectation of the issue results otherwise we can close the issue ..
