### ISSUE TITLE
Debounce user input to decrease unnecessary API calls

### ISSUE THREAD

**Issue by omeiirr** [MLH-Fellowship/prep-project-22.AUG.PREP.2#21]
We can use the Lodash [debounce](https://docs-lodash.com/v4/debounce/) function to only call the API once every few keystrokes, instead of calling it at every single keystroke. This would help reduce the number of API calls being made.

**Comment by omeiirr** [comment]
Or do we want to use the dropdown/auto-suggest field for selecting cities?

**Comment by ahmedsaed** [comment]
I fixed it by waiting until the user stops typing for 1 second then it sends the request 

I will push the code after the map changes are merged to avoid conflicts 

https://user-images.githubusercontent.com/37080003/184258592-9880d256-f402-4743-88dc-80bca3b54419.mp4
