### ISSUE TITLE
Improve weather card 

### ISSUE THREAD

**Issue by ahmedsaed** [MLH-Fellowship/prep-project-22.AUG.PREP.2#39]
Currently, the weather card only shows few info and it doesn't have any graphical elements 
![image](https://user-images.githubusercontent.com/37080003/184387354-9de912e2-622f-4332-b52b-c07d84b67206.png)

So after fixing issue #7, We should add more info from the API response to the card, we can also add some UI elements (clouds, sun etc.) to make it more visually appealing

**Comment by omeiirr** [comment]
[Here's](https://github.com/hicodersofficial/weather-app) a design inspiration 

![image](https://user-images.githubusercontent.com/54888682/184693676-72ac9346-f8be-4e8d-a522-8a377b31c7db.png)

**Comment by omeiirr** [comment]
I've added some extra fields to the weather card
![image](https://user-images.githubusercontent.com/54888682/185038385-ca9aac97-800f-44c7-b75f-c14db7e0ea6c.png)
