### ISSUE TITLE
The website doesn't seem to have an image to display when embedded

### ISSUE THREAD

**Issue by nightknighto** [MLH-Fellowship/prep-project-22.AUG.PREP.2#68]
You can test this by posting a link of the website (can use the github pages deployment) on [this link](https://metatags.io/). No image appears.
![image](https://user-images.githubusercontent.com/52013393/185236186-34dcf3c3-70e2-44b1-a74e-b6e3d2289bc6.png)

**Comment by omeiirr** [comment]
![image](https://user-images.githubusercontent.com/54888682/185604940-ec6b603b-408c-4368-8c4a-1f7bd22de249.png)

I'm adding this image as the cover image

**Comment by omeiirr** [comment]
I tried this but it doesn't seem to work 🤔 
```html
    <meta
      name="twitter:image"
      content="https://user-images.githubusercontent.com/54888682/185604940-ec6b603b-408c-4368-8c4a-1f7bd22de249.png"
    />
```

**Comment by nightknighto** [comment]
@omeiirr Looking at the pod portfolio website (which has this correctly set up), I can see there's this
```
    <meta property="og:image" content="assets/img/social-link.jpg">
    ```

**Comment by omeiirr** [comment]
metatags.io doesn't show this even for the portfolio project
![image](https://user-images.githubusercontent.com/54888682/185624182-dfa5eae5-651f-4bfa-a200-2a1eff9bcb56.png)

**Comment by nightknighto** [comment]
well... it used to work

**Comment by omeiirr** [comment]
Some issue with Netlify I assume

**Comment by nightknighto** [comment]
Seems fixed now
