### ISSUE TITLE
Improvements to Weather Card UI

### ISSUE THREAD

**Issue by nightknighto** [MLH-Fellowship/prep-project-22.AUG.PREP.2#74]
Currently looks like this:
![image](https://user-images.githubusercontent.com/52013393/185471247-466166f0-e9e9-466b-bb9e-3f4dfd202d87.png)

Can be greatly improved as mentioned in the comments of PR #64 
Maybe also give it a better background too or something

While at it, also vertically align the items in their cards
![image](https://user-images.githubusercontent.com/52013393/185471758-4e518c48-a9e6-4434-8e9d-fa42cd9ce2fe.png)

**Comment by omeiirr** [comment]
Incorporated all the suggestions mentioned in the previous PR. This is how it looks now:
![image](https://user-images.githubusercontent.com/54888682/185597056-4f257662-54e9-403a-9c25-6114b6ab23e8.png)

- Added a glassy effect to both, WeatherCard, and RequiredItems cards
- Centered the items 
- Decreased spacing between lines in the additional info
